name: 'Alternate Assign'
on:
  label:
    types: [created, edited]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: auto-assign
      - name: Build the action
        run: |
          cd ./.github/actions/auto-assign-action
          npm install  
          npm run build
          npm run package
      - name: User local auto assign action
        uses: ./.github/actions/auto-assign-action
        with:
          configuration-path: ".github/auto_assign.yml" # Only needed if you use something other than .github/auto_assign.yml
          run-number: ${{ github.run_number }}
