name: 'Alternate Assign'
on:
  pull_request
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: luisliuchao/alternate-assign-action@v1.1.2
        with:
          configuration-path: ".github/auto_assign.yml" # Only needed if you use something other than .github/auto_assign.yml
