name: 'Alternate Assign'
on:
  pull_request:
    types: [labeled]

jobs:
  add-reviews:
    if: ${{ github.event.label.name == 'my_label' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build the action
        run: |
          cd ./.github/actions/auto-assign-action
          npm install  
          npm run build
          npm run package
      - name: User local auto assign action
        uses: ./.github/actions/auto-assign-action
        with:
          configuration-path: ".github/auto_assign.yml" # Only needed if you use something other than .github/auto_assign.yml
          run-number: ${{ github.run_number }}
          webhook: ${{ secrets.SLACK_WEBHOOK }}
